version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7 (como se fosse a imagem do dockerfile)
    volumes:
      - db_data:/var/lib/mysql
    restart: always 
    env_file: # variaveis de ambiente 
      - ./config/db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "5000:80"
    restart: always  
    env_file:
      - ./config/wp.env
    networks:
      - backend
volumes:
  db_data: {}
networks:
   backend: bridge
